### ISSUE TITLE
File Descriptors not always closed.

### ISSUE THREAD

**Issue by bxm156** [axiak/java_posix_spawn#1]
Hello,

I have encountered an issue with the file descriptors not getting closed. When executing a process, I use a BufferedReader on the InputStream, so that I can read line by line. When the line == null, then that means the file descriptor was closed, and there is no more input. In most cases, this works fine. I recently encounted an issue when I the execve executes a bash script, which uses ifup. When ifup is called, it configures a wireless network using wpa_supplicant. Once a connection has been established, dhclient wlan0 is executed to get a new DHCP address. At the very end of the buffer, the messages are: 

ssh stopped/waiting
ssh start/running, process #####

After that, the execution hangs, because while the program script has executed, wpa_supplicant, dhclient, and ssh seem to have a hold on the STDOUT, and do not close it. This prevents the STDOUT from being closed, and therefore readLine will never return null, blocking program execution.

I attempted to correct the problem by modifying binrunner.c, and doing the execvp inside a seperate vfork, and letting the parent process wait till the child has terminated, and then clean up the file descriptors, but I wasn't able to get it to work successfully.

Any help would be greatly appreciated.

UPDATE: 
I forgot to mention that using Java's ProcessBuilder or Runtime.getRuntime.exec() methods do not encounter this problem.

**Comment by axiak** [comment]
Can you give me an example subcommand? I'll try to debug to see what the issue is. For instance, is

```
dhclient eth0
```

an example command?

**Comment by bxm156** [comment]
That command seems to work for me. I will put together some files, code, and logs for an example.

**Comment by bxm156** [comment]
Here is an archive of some logs, Java Code example, and bash scripts.

http://www.bryanmarty.com/wp-content/uploads/2012/01/posix_bug.zip

I will try to find a better example that is less dependent on my computer's configuration. The issue specifically occurs when you see the:

ssh stopped/waiting
ssh start/running, process #####

in the audit.log file i provided. You will see the code never reaches the log message that says "Done Reading" unlike the previous command that was executed (also in the audit.log file)

I recently moved all my Process.getRuntime.exec to the vFork implementation, and I noticed this issue. I also found that some commands I was sending to my printer from Java stopped working as well, but I'm not sure if its for the same reason. The only way that readLine returns NULL is when the Pipe is closed, so it must not be getting closed somehow.

**Comment by axiak** [comment]
Does this issue happen if you use the normal Java Runtime exec?

**Comment by bxm156** [comment]
No, everything works normally. The printer works, and the networking code works. The difference in the networking code is that I have it set to redirect Error to Input via Process Builder

**Comment by axiak** [comment]
It's really hard for me to condone using java for this sort of system maintenance ;-). That aside, perhaps there's a way we could create an abstract program that is behaving the same way as your subprocess? What exactly is your subprocess doing?
For instance, is this equivalent to your subprocess?

```
perl -e 'sleep 1000000;'
```

**Comment by bxm156** [comment]
Haha, I agree with you on that one, but I don't really have much of a choice. I can create a program using the code I already have. The sub processes that get launched could do a variety of things, specifically they configure network settings and output information to stdout. We may be able to replicate the issue by creating a small c program, to see if it is indeed a process that is not closing File Descriptors, which seems to be the most obvious reason for readLine not returning NULL.

**Comment by bxm156** [comment]
I have been able to isolate the issue to dhclient and I have made an example. I will post an example on GitHub soon.

**Comment by bxm156** [comment]
I have uploaded two projects. I was able to get the issue to occur with dhclient. On the system where the issue is happening, it seems to also happen without using dhclient, and a printer is also affected, so I don't think its dhclient itself is the cause, but I was able to get the issue to occur using it. I added two projects on Github:

CSpawn - https://github.com/bxm156/CSpawn
JSpawn - https://github.com/bxm156/JSpawn

CSpawn is used to build an executable that seems to simulate the issue, the executable forks a dhclient
JSpawn is the reader.

When useing the built in java exec, I am able to see the dhclient output on stdout. When using the posix_spawn implementation, it hangs trying to read the input stream. The posix_spawn implementation works fine for a command such as: ls

**Comment by axiak** [comment]
Honestly, I feel as though you've a spent a lot of time writing stuff
that is kind of extraneous. What I really care about is: What about
dhclient is causing this issue? Can you describe what the dhclient
program is doing? E.g. is it just reading blindly from stdin? It
should be possible to write a 6 line python/perl/ruby/shell script to
simulate dhclient here.

-Mike

On Sun, Jan 22, 2012 at 6:17 PM, Bryan Marty
reply@reply.github.com
wrote:

**Comment by bxm156** [comment]
I discovered the problem. The embedded system I am working on has a main java process, with a lot of file descriptors, some for outputting stderr and stdout to logs. When exec is done, file descriptors are copied. I noticed that my dhclient had file descriptors for everything in the main Java process. The file descriptors from the main JAVA process (which contained streams to say the printer), were copied to dhclient. Since dhclient is a service running in the background, it stays open. So, the printer command were to execute, (vforking and execing), the printer command would also have the same copied file discriptors. When the descriptor for the printer command closed, an EOF did not occur, since the dhclient's file descriptor was still open.

By closing all file descriptors except 0 1 2 before the exec in binrunner, everything began working just like Runtime.getRuntime.exec().

Thanks for your time. If you interested in the change, I can submit a Pull Request

**Comment by axiak** [comment]
Great find. I'm glad you isolated the error, I'll push an update in a
few minutes.

On Sun, Jan 22, 2012 at 11:22 PM, Bryan Marty
reply@reply.github.com
wrote:

**Comment by axiak** [comment]
It's actually surprisingly difficult to close all necessary file
descriptors in a safe, quick, and portable way. I'll get something out
by the end of the weekend.

Also, I read your blog and you should probably read more about
posix_spawn. It's not entirely correct to say that posix_spawn is
replaced by vfork since vfork is actually how posix_spawn is
implemented (I would send a link to the glib source code, but google
code search is closed :-().

vfork is actually safe as long as you do nothing besides _exit and
execve immediately after vfork (which is what we do).

When writing this library, I discovered that posix_spawn is a bit of a
red herring, but everyone believes it fixes everything. What posix
spawn provides is a neat little api for specifying how you want file
descriptors to be moved before the exec to the child process. Only
problem is, if you do ever try to do any file descriptor operations,
posix_spawn will call fork() rather than vfork(). The binrunner is
really the reason why this all works, and linux/posix does not have a
magical binrunner to use.

Regards,
Mike

-Mike

**Comment by bxm156** [comment]
Your correct, posix spawn doesn't replace vfork. I didn't mean to give that impression. I mean to say that the source code here doesn't use the posix_spawn function, but instead uses vfork(), since posix_spawn isn't implemented using vfork across all Linux distributions. I agree that vfork() is safe, as long as you exec right after, which is what this code does. I was just stating for general people that vfork(), when used in the wrong way, can lead to problems. I will clarify that in my post.
