### ISSUE TITLE
binrunner not respecting user's paths

### ISSUE THREAD

**Issue by csmart** [axiak/java_posix_spawn#3]
Firstly, thank you for java_posix_spawn!

I have an issue when a java process (running Oracle JRE under Fedora) uses posix-spawn to call a bash script it doesn't appear to be respecting my user's path (running as root).

If I tell the script to echo out the $PATH it seems to show the default Fedora path, which made me echo out $USER and it was empty.

Any ideas? Thanks!

**Comment by axiak** [comment]
I think this is an unfortunate consequence of the multiple execve strategy. Can you source your bash config in your subprocess?

**Comment by csmart** [comment]
Hi Michael, thanks for the reply. I will try and see how it goes..
